apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/kubernetes/ingress-nginx.git/deploy/static/provider/aws?ref=controller-v0.44.0
  - ./k8s/helloworldapp
  - ./k8s/external-dns
  - ./k8s/cert-manager
