apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.7.6

resources:
  - namespace.yaml

patches:
  - deployment.yaml

namespace: external-dns